### ISSUE TITLE
Feature Request: Improve Documentation for Image to Video Conversion

### ISSUE THREAD

**Issue by klumsy** [StartAutomating/RoughDraft#83]
Rather than having to rely on a few steps and knowing all the fine tuned settings a top level cmdlet might be useful to do this. That does something like this. 

At least with defaults and being able to override settings if people want to do different things.  

ffmpeg -r 0.01 -loop 1 -i bkg2.png -i audiotest.m4a -c:v libx264 -tune stillimage -preset  ultrafast -pix_fmt yuv420p  -shortest out4.mp4 -y

**Comment by StartAutomating** [comment]
In general RoughDraft is designed to have as few commands as possible, so I'm not sure an isolated command makes sense at this point.

Convert-Media will get an update example of this particular scenario.
